/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroupRouteImport } from './routes/group'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProofRouteImport } from './routes/proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/proof': typeof ProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/proof': typeof ProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/proof': typeof ProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/contact'
    | '/group'
    | '/insights'
    | '/privacy'
    | '/product'
    | '/proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/contact'
    | '/group'
    | '/insights'
    | '/privacy'
    | '/product'
    | '/proof'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/contact'
    | '/group'
    | '/insights'
    | '/privacy'
    | '/product'
    | '/proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  GroupRoute: typeof GroupRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  ProofRoute: typeof ProofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  GroupRoute: GroupRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  ProofRoute: ProofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
